# Generated by Django 5.0.3 on 2024-03-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0002_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='documents',
            new_name='document',
        ),
    ]
